### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

### ISSUE THREAD

**Issue by F34140r** [LiquidHelium/atom-clang-format#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.18.7-200.fc21.x86_64
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

```
At /usr/share/atom/resources/app/src/pane.js:782

TypeError: Cannot read property 'getScopeDescriptor' of undefined
    at TextEditor.module.exports.TextEditor.scopesAtCursor (/usr/share/atom/resources/app/src/text-editor.js:2474:34)
    at TextEditor.module.exports.TextEditor.getCursorScopes (/usr/share/atom/resources/app/src/text-editor.js:2479:19)
    at /home/feanor/.atom/packages/clang-format/lib/clang-format.coffee:37:26
    at TextBuffer.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:620:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:542:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:525:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:677:35)
```

### Commands

```
  7x -3:16.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:04.3 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:03.7 core:backspace (atom-text-editor.editor.is-focused)
     -3:02.7 editor:newline (atom-text-editor.editor.is-focused)
 13x -3:01.7 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.1 editor:newline (atom-text-editor.editor.is-focused)
 17x -2:38.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:25.6 core:move-down (atom-text-editor.editor.is-focused)
     -2:25.5 core:move-up (atom-text-editor.editor.is-focused)
     -2:25.2 core:backspace (atom-text-editor.editor.is-focused)
     -2:23.8 core:move-left (atom-text-editor.editor.is-focused)
     -2:23.4 core:move-down (atom-text-editor.editor.is-focused)
     -2:23.1 core:backspace (atom-text-editor.editor.is-focused)
     -2:21.5 core:save (atom-text-editor.editor.is-focused)
     -0:06.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
autocomplete-clang, v0.6.2
clang-format, v1.8.0
linter-clang, v2.25.1

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
I can't replicate this

**Comment by flungo** [comment]
I seem to get this when using split pane. Will provide more information if I get any.

**Comment by leidegre** [comment]
Getting this issue as well. Appears that there's something with the right pane. Doesn't happen otherwise.

**Comment by LiquidHelium** [comment]
Ah thank you both, I can replicate this now. I'll look into it and hopefully have a fix up soon.
