### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by LiquidHelium** [LiquidHelium/atom-clang-format#22]
[Enter steps to reproduce below:]

1. Something to do with multiple panes
2. ...

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\pane.js:759

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\text-editor.js:1319:34)
  at ClangFormat.module.exports.ClangFormat.getCurrentCursorPosition (C:\Users\Andrew\.atom\packages\clang-format\lib\clang-format.coffee:72:29)
  at ClangFormat.module.exports.ClangFormat.format (C:\Users\Andrew\.atom\packages\clang-format\lib\clang-format.coffee:34:17)
  at C:\Users\Andrew\.atom\packages\clang-format\lib\clang-format.coffee:25:10
  at Emitter.module.exports.Emitter.emit (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:917:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\text-editor.js:592:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Andrew\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
 11x -1:47.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:17.5.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -1:16.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:10 clang-format:format (atom-text-editor.editor.is-focused)
  2x -1:08.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:55.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:02.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "clang-format": {}
}
```

### Installed Packages

```coffee
# User
clang-format, v1.10.0

# Dev
No dev packages
```

**Comment by ipuustin** [comment]
Still happened for me using 1.13.0.

**Comment by rpavlik** [comment]
Still happening with the latest version
