### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\sim\...

### ISSUE THREAD

**Issue by SimDietrich** [LiquidHelium/atom-clang-format#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\sim\Perforce\simd_SIM2-TALON_4066\depot\Software\OculusSDK\PC\Main\PyLibOVR\pyCamera.cpp

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\sim\Perforce\simd_SIM2-TALON_4066\depot\Software\OculusSDK\PC\Main\PyLibOVR\pyCamera.cpp
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (C:\Users\sim\.atom\packages\clang-format\lib\clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (C:\Users\sim\.atom\packages\clang-format\lib\clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sim\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\sim\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\sim\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\sim\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
  2x -1:58.7.0 minimap:toggle (div.deprecation-cop.pane-item.native-key-bindings)
     -1:29.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:25.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:01.3.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:54.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 clang-format:format (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-mcs",
      "linter-mcs",
      "linter-mcs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.7.0
autocomplete-glsl, v0.2.3
clang-format, v1.14.0
color-picker, v2.0.7
hex, v0.6.2
language-batch, v0.3.3
language-glsl, v2.0.0
language-hlsl, v1.1.1
language-opencl, v0.1.1
language-shadercode, v2.0.0
language-sln, v0.1.0
linter-clang, v2.26.0
minimap, v4.10.0
minimap-git-diff, v4.1.3
pigments, v0.8.0

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
