### ISSUE TITLE
Uncaught Error: spawnSync /bin/sh EPIPE

### ISSUE THREAD

**Issue by tbetcke** [LiquidHelium/atom-clang-format#30]
[Enter steps to reproduce below:]

Press Cmd-Shift-K to activate clang-format

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0
### Stack Trace

Uncaught Error: spawnSync /bin/sh EPIPE

```
At child_process.js:1377

Error: spawnSync /bin/sh EPIPE
  at exports._errnoException (util.js:734:11)
  at spawnSync (child_process.js:1313:20)
  at execSync (child_process.js:1368:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/betcke/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (/Users/betcke/.atom/packages/clang-format/lib/clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -1:41.4.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:31.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 clang-format:format (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "clang-format": {}
}
```
### Installed Packages

``` coffee
# User
clang-format, v1.14.0

# Dev
No dev packages
```

**Comment by JianxinMa** [comment]
I also encounter this problem today when I open Atom by clicking the icon. However, when I open Atom by typing "atom" on the terminal, everything works fine.

**Comment by h3h** [comment]
I'm seeing the same issue, regardless of whether I launch Atom via Finder or Terminal.

1. Hit CMD+Shift+K to run clang-format

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package 1.29.0


### Stack Trace

Uncaught Error: spawnSync /bin/sh EPIPE

```
At /Users/bfults/Dropbox (Personal)/Backups/Atom/packages/clang-format/lib/clang-format.coffee:85

Error: spawnSync /bin/sh EPIPE
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at execSync (child_process.js:529:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
    at ClangFormat.module.exports.ClangFormat.format (/packages/clang-format/lib/clang-format.coffee:75:16)
    at /packages/clang-format/lib/clang-format.coffee:18:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -9:10.2.0 clang-format:format (input.hidden-input)
```

### Non-Core Packages

```
atom-wrap-in-tag 0.6.0 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
clang-format 1.29.0 
elm-format 2.2.0 
elmjutsu 5.6.0 
intentions 1.1.2 
language-elm 1.5.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-elm-make 0.23.5 
linter-python 3.1.2 
linter-ui-default 1.6.3 
python-indent 1.1.0 
sort-lines 0.14.0 
toggle-quotes 1.0.1 
```

**Comment by MatthiasKunick** [comment]
Even though this was reported 18 months ago:
I ran into this issue since the executable path of clang-format (clang-format/settings) was not correct anymore after I updated my compiler.

**Comment by LiquidHelium** [comment]
Thank you for reporting this and thank you @MatthiasKunick for helping diagnose it. Sorry for not being more involved in trying to help. I think the core issue with this and other tickets here with similar error messages is that the package doesn't give a detailed enough error message to point people in the correct direction and different errors can give the same message. I'm going to work on improving this.
