### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=2037 -lines=1:66 -assume-filenam...

### ISSUE THREAD

**Issue by bunnyblue** [LiquidHelium/atom-clang-format#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=2037 -lines=1:66 -assume-filename=/Users/BunnyBlue/Documents/openSource/OpenAtlasExtension/buildTools/NG/AaptExt/AaptExt/CodeGen.cpp

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=2037 -lines=1:66 -assume-filename=/Users/BunnyBlue/Documents/openSource/OpenAtlasExtension/buildTools/NG/AaptExt/AaptExt/CodeGen.cpp
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/BunnyBlue/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (/Users/BunnyBlue/.atom/packages/clang-format/lib/clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:32.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.9.0 clang-format:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
clang-format, v1.14.0
formatter, v2.12.3
markdown-format, v2.5.1

# Dev
No dev packages
```

**Comment by MatteoRagni** [comment]
[Enter steps to reproduce below:]

1. Install **clang-format**
2. Modify a C/C++ file and save

**Atom Version**: 1.0.2
**System**: Debian GNU/Linux
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0


### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=808 -assume-filename=/home/nirvana1289/workspace/gcode2/dynamic_address.h

```
At /usr/share/atom/resources/app.asar/src/pane.js:774

Error: Command failed: clang-format -style=file -cursor=808 -assume-filename=/home/nirvana1289/workspace/gcode2/dynamic_address.h
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/home/nirvana1289/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at /home/nirvana1289/.atom/packages/clang-format/lib/clang-format.coffee:25:29
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at /home/nirvana1289/.atom/packages/clang-format/lib/clang-format.coffee:25:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:42.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:42.3.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:15 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:12.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:11.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:05.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:49.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:46.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43 settings-view:view-installed-packages (atom-text-editor.editor)
     -0:34.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false,
    "projectHome": "/home/nirvana1289/workspace",
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.2
clang-format, v1.14.0
color-picker, v2.0.10
fonts, v0.5.0
language-bison, v1.0.0
language-latex, v0.6.1
language-lex-flex, v0.1.0
last-cursor-position, v0.9.0
latex, v0.25.0
markdown-preview-plus, v1.6.0
minimap, v4.11.2
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
useful-context-menu, v0.2.1

# Dev
No dev packages
```

**Comment by MatteoRagni** [comment]
**SOLVED**: clang-format was installed with name: clang-format-3.7 in my system. Created a symbolic link and all worked like a charm (the problem was a binary not found)

**Comment by radkin** [comment]
A few specifics regarding the above. 

1. In atom (1.1.0) I was seeing the message "Doesn't bundle the clang-format executable for your platform(darwin_x64). Consider installing it with your native package manager instead." 
It wasn't clear which package was generating this message as I had not installed "clang" anything. 
2. What I found was that the "atom-format" package said "..according to clang-format" in the description and that is what tipped me off. 
3. If you brew install "clang-format" or install by other means, it will install in some location other than where it expects it to be (per above). The following symbolic link worked for me

ln -s /usr/local/bin/clang-format /Users/yourName/.atom/packages/atom-format/bin/darwin_x64/clang-format
