### ISSUE TITLE
Uncaught Error: spawnSync C:\WINDOWS\system32\cmd.exe EOF

### ISSUE THREAD

**Issue by squall1988** [LiquidHelium/atom-clang-format#35]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0
### Stack Trace

Uncaught Error: spawnSync C:\WINDOWS\system32\cmd.exe EOF

```
At C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:774

Error: spawnSync C:\WINDOWS\system32\cmd.exe EOF
  at exports._errnoException (util.js:734:11)
  at spawnSync (child_process.js:1313:20)
  at execSync (child_process.js:1368:13)
  at ClangFormat.module.exports.ClangFormat.format (C:\Users\lilon\.atom\packages\clang-format\lib\clang-format.coffee:59:14)
  at C:\Users\lilon\.atom\packages\clang-format\lib\clang-format.coffee:25:29
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:740:18)
  at C:\Users\lilon\.atom\packages\clang-format\lib\clang-format.coffee:25:16
  at Emitter.module.exports.Emitter.emit (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\lilon\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
     -0:06.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
clang-format, v1.14.0
language-latex, v0.6.1

# Dev
No dev packages
```

**Comment by chufreud** [comment]
I have the same problem,anyone know why?

**Comment by LiquidHelium** [comment]
I'm going to close this issue because I can't help diagnose it because the error messages the package spits out aren't detailed enough. I'm going to work on the error messages in the package.
