### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=375 -assume-filename=/home/nylon...

### ISSUE THREAD

**Issue by Nyloner** [LiquidHelium/atom-clang-format#36]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=375 -assume-filename=/home/nylone/C/7.c

```
At /usr/share/atom/resources/app.asar/src/pane.js:774

Error: Command failed: clang-format -style=file -cursor=375 -assume-filename=/home/nylone/C/7.c
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/home/nylone/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at /home/nylone/.atom/packages/clang-format/lib/clang-format.coffee:25:29
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at /home/nylone/.atom/packages/clang-format/lib/clang-format.coffee:25:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:12.5.0 core:save (input.hidden-input)
     -1:10.7.0 python-debugger:insert (input.hidden-input)
  3x -0:42 python-debugger:remove (input.hidden-input)
     -0:37.4.0 core:backspace (input.hidden-input)
     -0:36 snippets:next-tab-stop (input.hidden-input)
     -0:36 snippets:expand (input.hidden-input)
     -0:36 editor:indent (input.hidden-input)
     -0:34.2.0 python-debugger:remove (input.hidden-input)
     -0:33 core:save (input.hidden-input)
  7x -0:32 python-debugger:insert (input.hidden-input)
undefined -0:24.5.0 core:backspace (input.hidden-input)
     -0:08.6.0 core:move-down (input.hidden-input)
     -0:08.3.0 core:backspace (input.hidden-input)
     -0:03.4.0 core:save (input.hidden-input)
     -0:01.1.0 core:backspace (input.hidden-input)
     -0:00.4.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
atom-python-debugger, v0.3.4
clang-format, v1.14.0
color-picker, v2.0.11
language-cuda, v0.0.0
linter-clang, v2.26.2
linter-pylint, v0.2.2
minimap, v4.12.0

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
