### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\Cand...

### ISSUE THREAD

**Issue by anas2660** [LiquidHelium/atom-clang-format#37]
[Enter steps to reproduce below:]

1. Make new project and add a new main file.
2. Save the file.

**Atom Version**: 1.0.2
**System**: Unknown Windows Version                (I actually have: Windows 7 Home Premium)
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\Candfa\Documents\My Cpp Projects\AtomCpp\Main.cpp

```
At C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:774

Error: Command failed: clang-format -style=file -cursor=0 -assume-filename=C:\Users\Candfa\Documents\My Cpp Projects\AtomCpp\Main.cpp
    at checkExecSyncError (child_process.js:1334:13)
    at execSync (child_process.js:1374:13)
    at ClangFormat.module.exports.ClangFormat.format (C:\Users\Candfa\.atom\packages\clang-format\lib\clang-format.coffee:84:16)
    at C:\Users\Candfa\.atom\packages\clang-format\lib\clang-format.coffee:40:28
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:740:18)
    at C:\Users\Candfa\.atom\packages\clang-format\lib\clang-format.coffee:39:27
    at Emitter.module.exports.Emitter.emit (C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:985:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Candfa\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:579:26)
```

### Commands

```
     -0:06.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "clang-format": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
autocomplete-glsl, v0.2.3
autocomplete-paths, v1.0.2
clang-format, v1.14.0
language-glsl, v2.0.0
linter, v1.2.4
linter-clang, v2.26.2
linter-cpplint, v0.1.4
refactor, v0.5.1
you-complete-me, v0.5.0

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
