### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=99 -assume-filename=/Users/rs/Wo...

### ISSUE THREAD

**Issue by ravsom** [LiquidHelium/atom-clang-format#38]
1. Devised an html page and clicked on Clang format

**Atom Version**: 1.0.2
**System**: Mac OS X 10.9.5
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=99 -assume-filename=/Users/rs/Working/ReactJs/react-0.13.3/helloworld.html

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=99 -assume-filename=/Users/rs/Working/ReactJs/react-0.13.3/helloworld.html
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/rs/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (/Users/rs/.atom/packages/clang-format/lib/clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:11.6.0 snippets:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:59.1.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -2:54.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:52.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.8.0 styleguide:show (atom-text-editor.editor.is-focused)
     -0:43.5.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:26.9.0 timecop:view (atom-text-editor.editor.is-focused)
     -0:18.7.0 jsformat:format (atom-text-editor.editor.is-focused)
     -0:00.7.0 clang-format:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.18.0
clang-format, v1.14.0
jsformat, v0.9.0
language-babel, v0.10.2
react, v0.12.6
react-snippets, v0.1.4

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
