### ISSUE TITLE
Doesn't work with spaces in paths

### ISSUE THREAD

**Issue by martinfinke** [LiquidHelium/atom-clang-format#39]
1. Open a .h file that's in a path containing spaces
2. Run clang-format to format the file

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=105 -assume-filename=/Users/martin/Desktop/Neuer Ordner/Foo/repo/Bar/main.h

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=105 -assume-filename=/Users/martin/Desktop/Neuer Ordner/Foo/repo/Bar/main.h
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/martin/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (/Users/martin/.atom/packages/clang-format/lib/clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

Running the above command manually from the Terminal fails, saying the file couldn't be found. Maybe the path should be in quotes?

**Comment by LiquidHelium** [comment]
fixed by 1fa50c4a5606428652035a668a2dc91154447a68
