### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=1875 -lines=1:69 -assume-filenam...

### ISSUE THREAD

**Issue by ayodejiige** [LiquidHelium/atom-clang-format#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=1875 -lines=1:69 -assume-filename=/home/dj/Documents/Projects/BigInt/Source/big_int.h

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=1875 -lines=1:69 -assume-filename=/home/dj/Documents/Projects/BigInt/Source/big_int.h
    at checkExecSyncError (child_process.js:1334:13)
    at execSync (child_process.js:1374:13)
    at ClangFormat.module.exports.ClangFormat.format (/home/dj/.atom/packages/clang-format/lib/clang-format.coffee:84:16)
    at atom-workspace.<anonymous> (/home/dj/.atom/packages/clang-format/lib/clang-format.coffee:21:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
  8x -0:13.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.7.0 clang-format:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "clang-format": {
    "formatObjectiveCOnSave": false,
    "formatJavascriptOnSave": false,
    "formatCPlusPlusOnSave": false,
    "formatCOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
clang-format, v1.14.0

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
