### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=2970 -lines=1:128 -assume-filena...

### ISSUE THREAD

**Issue by BoilerMaker2015** [LiquidHelium/atom-clang-format#41]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.2
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=2970 -lines=1:128 -assume-filename=/Users/macuser/Desktop/杂/251/lab2-src/gethttp.cpp

```
At child_process.js:1377

Error: Command failed: clang-format -style=file -cursor=2970 -lines=1:128 -assume-filename=/Users/macuser/Desktop/杂/251/lab2-src/gethttp.cpp
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/macuser/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at atom-workspace.<anonymous> (/Users/macuser/.atom/packages/clang-format/lib/clang-format.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/macuser/Desktop/download_save/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Users/macuser/Desktop/download_save/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/macuser/Desktop/download_save/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Users/macuser/Desktop/download_save/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:31.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:29.8.0 project-find:show (atom-text-editor.editor.is-focused)
     -4:12.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:57.2.0 core:select-all (atom-text-editor.editor.is-focused)
  2x -2:54.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:51.3.0 project-find:show (atom-text-editor.editor.mini.is-focused)
  2x -2:47.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:53.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.7.0 clang-format:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
clang-format, v1.14.0
linter, v1.2.4
linter-clang, v2.26.2
linter-cpplint, v0.1.4

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
