### ISSUE TITLE
Uncaught Error: Command failed: clang-format -style=file -cursor=1232 -assume-filename=/Users/krz...

### ISSUE THREAD

**Issue by naosoft** [LiquidHelium/atom-clang-format#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.14.0

### Stack Trace

Uncaught Error: Command failed: clang-format -style=file -cursor=1232 -assume-filename=/Users/krzysiek/Workbeanch/ESP/mqttServer/server2.js

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

Error: Command failed: clang-format -style=file -cursor=1232 -assume-filename=/Users/krzysiek/Workbeanch/ESP/mqttServer/server2.js
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/krzysiek/.atom/packages/clang-format/lib/clang-format.coffee:59:14)
  at /Users/krzysiek/.atom/packages/clang-format/lib/clang-format.coffee:25:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:751:18)
  at /Users/krzysiek/.atom/packages/clang-format/lib/clang-format.coffee:25:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:995:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:511:23)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:457:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:435:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:47 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:46 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -2:44.4.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:42.9.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:38.9.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -2:38.5.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
  3x -2:19 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -2:18.4.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -2:12.4.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:33.9.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:28.2.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:30.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:11.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:10.7.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.8.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:06.7.0 core:close (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "visual-studio-code",
      "one-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-text-transformer, v0.7.0
atom-yeoman, v0.3.11
autocomplete-emp-lua, v0.8.0
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
clang-format, v1.14.0
color-picker, v2.0.11
dart-tools, v0.9.23
express-complete, v0.2.0
highlight-line, v0.11.0
javascript-standard-snippets, v0.2.1
jsformat, v0.9.0
language-arduino, v0.3.1
language-clojure, v0.16.0
language-csharp, v0.6.0
language-dart, v0.2.0
language-gmod-lua, v0.3.1
language-ino, v0.1.0
language-javascript-semantic, v0.2.1
language-lua, v0.9.4
language-rust, v0.4.4
language-scala, v1.1.3
linter, v1.2.4
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.2
minimap, v4.12.1
node-debugger, v1.1.7
nodejs-snippets, v1.0.2
omnisharp-atom, v0.22.6
pretty-json, v0.4.1
standard-formatter, v1.1.0
vim-mode, v0.57.0
visual-studio-code, v0.4.0

# Dev
No dev packages
```

**Comment by LiquidHelium** [comment]
Possibly fixed by 1fa50c4a5606428652035a668a2dc91154447a68 reopen is still happening
