### ISSUE TITLE
Uncaught Error: spawnSync /bin/sh ENOENT

### ISSUE THREAD

**Issue by pallotron** [LiquidHelium/atom-clang-format#49]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.18.0

### Stack Trace

Uncaught Error: spawnSync /bin/sh ENOENT

```
At /Users/pallotron/.atom/packages/clang-format/lib/clang-format.coffee:75

Error: spawnSync /bin/sh ENOENT
  at exports._errnoException (util.js:837:11)
  at spawnSync (child_process.js:432:20)
  at execSync (child_process.js:487:13)
  at ClangFormat.module.exports.ClangFormat.format (/Users/pallotron/.atom/packages/clang-format/lib/clang-format.coffee:65:16)
  at atom-workspace.<anonymous> (/Users/pallotron/.atom/packages/clang-format/lib/clang-format.coffee:16:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:01.5.0 clang-format:format (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view",
      "minimap-autohide",
      "nuclide-clang-atom"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "clang-format": {
    "formatCOnSave": false,
    "formatCPlusPlusOnSave": false,
    "formatJavascriptOnSave": false,
    "formatObjectiveCOnSave": false,
    "executable": "/usr/local/bin/clang-format"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-python, v1.0.1
clang-format, v1.18.0
file-icons, v1.6.13
file-types, v0.5.1
go-plus, v3.5.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.1
hyperclick, v1337.0.0-18731106
language-babel, v2.6.0
language-ini, v1.14.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
minimap, v4.18.0
python-autopep8, v0.1.3
python-yapf, v0.9.1
tool-bar, v0.1.9
vim-mode, v0.63.0
vim-mode-visual-block, v0.2.14

# Dev
No dev packages
```

**Comment by artagnon** [comment]
What was the resolution of this issue? I'm seeing it now.

**Comment by LiquidHelium** [comment]
This issue was due to not finding clang-format I think, but was fixed because clang-format is now bundled. Likley your issue is different from this. If you could create a new issue with your trace/details/packages etc I'll look into it.

**Comment by iBeliever** [comment]
I just got this error. I think it's because I moved the file I was editing to a different directory but Atom was trying to save the open file to the original path which didn't exist anymore.

**Comment by sthilden** [comment]
I am getting this error, and can confirm that @iBeliever is right on the cause.

Steps to reproduce:
1. Open a file
2. Change name of the folder where file is located
3. Run "Clang Format: Format" on the file

I am running Atom v.1.8.0 and clang-format v.1.25.0 on Ubuntu 16.04.

**Comment by DamienGong** [comment]
got the same issue

**Comment by thezhangwei** [comment]
Seeing the same issue here
