### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by boazsegev** [LiquidHelium/atom-clang-format#63]
This is mostly an automated issue... it might not be a bug as much as an implementation limitation related to nested structures...

[Enter steps to reproduce below:]

1. ~~Create a script to take an array, make it into a binary tree and output a hardcoded binary tree into a static const variable (I was trying to optimize an HPACK decoder). I'll attach the script in a second.~~

2. ~~Add the code for the static binary tree to a C file.~~

3. Download [the header file from this link](https://github.com/boazsegev/facil.io/blob/master/src/http/unused/hpack_data.h) and open it in Atom.

3. Wait a while and watch it all burn... the issue crashes the formatting package and prevents the file from being saved.

~~This was the script (I wrote it in C because I was lazy... sorry about that)~~ **edit**: removed, [find a copy here](https://github.com/boazsegev/facil.io/blob/master/src/http/unused/hpack_data.h).

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package, v1.25.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1030

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at ClangFormat.module.exports.ClangFormat.getReturnedCursorPosition (/Users/2be/.atom/packages/clang-format/lib/clang-format.coffee:113:19)
    at ClangFormat.module.exports.ClangFormat.format (/Users/2be/.atom/packages/clang-format/lib/clang-format.coffee:78:28)
    at /Users/2be/.atom/packages/clang-format/lib/clang-format.coffee:28:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at /Users/2be/.atom/packages/clang-format/lib/clang-format.coffee:28:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1132:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -6:18 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -6:11.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:08.0 core:close (div.package-detail.panels-item)
     -3:03.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -2:51.3.0 core:close (atom-text-editor.editor.is-focused)
     -1:14.7.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "clang-format": {
    "formatJavascriptOnSave": true,
    "formatObjectiveCOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
auto-detect-indentation, v1.3.0 (active)
autocomplete-clang, v0.10.0 (active)
clang-format, v1.25.0 (active)
language-slim, v0.5.0 (active)
linter, v1.11.18 (active)
linter-clang, v3.4.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by boazsegev** [comment]
I uploaded [the C (actually a `.h`) file](https://github.com/boazsegev/facil.io/blob/master/src/http/unused/hpack_data.h) to GitHub, to make it easier to recreate the issue.

Simply download the file and test in Atom.

I updated the original issue text accordingly.

**Comment by LiquidHelium** [comment]
Thanks for the detailed bug report boazsegev!

This seems to be a problem with clang-format, not with my atom wrapper. If I try to run clang-format on your file from the command line I get an error, my wrapper then crashes when it doesn't know how to handle it:

`
0x770AA832 (0xE06D7363 0x00000001 0x00000003 0x019FD278) <unknown module>
0x72EA9339 (0x019FD294 0x72EBC7FC 0x72EBD1CC 0x72EBC7EC) <unknown module>
0x72EEDA6A (0x000013E8 0x00C3CAC6 0x00000062 0x00000000) <unknown module>
0x00C30B8B (0x7E0BFD90 0x7E0BFDB0 0x7E0BFD78 0x00C3CE10) <unknown module>
0x00C3C720 (0x09594C18 0x7E0BFD78 0x00000000 0x019FD334) <unknown module>
0x00C3CFBF (0x019FD374 0x019FD400 0x058E7EA8 0x00000001) <unknown module>
0x00C3D7D8 (0x058E7EA8 0x00000000 0x019FD400 0x019FD650) <unknown module>
0x00C3D2AC (0x019FD4DC 0x0246C508 0x019FDA7C 0x21691F0B) <unknown module>
0x00C2BEF2 (0x019FDB4C 0x770112BC 0x00000000 0x0000000F) <unknown module>
0x77096CFC (0x00000000 0x7E421A36 0x00000000 0x0000000F) <unknown module>
`

I will update my atom wrapper to better handle this error instead of throwing a JSON parsing one, but I can't actually make it work on this file. You'll need to file a bug report to the clang-format people over at llvm.org/bugs

**Comment by boazsegev** [comment]
Cool! Thanks for the quick reply.

👍
