### ISSUE TITLE
[Bug] Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ooJerryLeeoo** [LiquidHelium/atom-clang-format#67]
Duplicated with #63 but the problem is still not fixed.

[Enter steps to reproduce:]

1. Open a `C++` file.
2. Press <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>k</kbd>.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package 1.28.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At ~/.atom/packages/clang-format/lib/clang-format.coffee:85

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at ClangFormat.module.exports.ClangFormat.getReturnedCursorPosition (/packages/clang-format/lib/clang-format.coffee:116:19)
    at ClangFormat.module.exports.ClangFormat.format (/packages/clang-format/lib/clang-format.coffee:79:28)
    at /packages/clang-format/lib/clang-format.coffee:18:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:37 markdown-preview:toggle (input.hidden-input)
     -2:35.6.0 pane:show-next-item (input.hidden-input)
  2x -2:35.2.0 markdown-preview:toggle (input.hidden-input)
     -2:33.2.0 core:close (input.hidden-input)
     -2:32 window:focus-pane-on-left (input.hidden-input)
     -2:30.5.0 window:focus-pane-on-right (input.hidden-input)
     -2:29.9.0 core:close (div.markdown-preview.native-key-bindings)
     -2:26.9.0 core:save (input.hidden-input)
     -2:26.4.0 core:select-all (input.hidden-input)
     -2:26.3.0 core:backspace (input.hidden-input)
     -2:26 core:save (input.hidden-input)
     -2:25.1.0 clang-format:format (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
clang-format 1.28.0 
intentions 1.1.2 
linter 2.1.2 
linter-clang 3.4.9 
linter-ui-default 1.2.2 
```

**Comment by ooJerryLeeoo** [comment]
I've found the problem is `clang-format` format when file empty.
