### ISSUE TITLE
Failed to load the clang-format package

### ISSUE THREAD

**Issue by P-EKKA** [LiquidHelium/atom-clang-format#72]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package 1.29.0

### Stack Trace

Failed to load the clang-format package

```
At Cannot find module 'clang-format'

Error: Cannot find module 'clang-format'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-clang-format-master/lib/clang-format.coffee:5:26)
    at /packages/atom-clang-format-master/lib/clang-format.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-clang-format-master/lib/main.coffee:1:15)
    at /packages/atom-clang-format-master/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:473:25)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:812:34
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.1 
clang-format 1.29.0 
autocomplete-clang 0.11.3 
busy-signal 1.4.3 
gcc-make-run 0.2.9 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
simplified-chinese-menu 5.3.4 
```

**Comment by LiquidHelium** [comment]
i think this should be fixed now as of 2.0.5
