### ISSUE TITLE
Fails on remote files

### ISSUE THREAD

**Issue by sweeneychris** [LiquidHelium/atom-clang-format#75]
I'm using Nuclide with Atom, which provides an easy-to-use remote development utility. When I am editing files on a remote server, clang-format fails and outputs the following errors. Seems to be related to https://github.com/LiquidHelium/atom-clang-format/issues/49 but I wanted to create a new issue since this behavior is for remote file editing.

[Enter steps to reproduce:]

1. Open file on remote server.
2. Run clang-format

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package 1.29.0

### Stack Trace

Uncaught Error: spawnSync /bin/sh ENOENT

```
At /Users/csweeney/.atom/packages/clang-format/lib/clang-format.coffee:89

Error: spawnSync /bin/sh ENOENT
  at exports._errnoException (util.js:1026:11)
  at spawnSync (child_process.js:473:20)
  at execSync (child_process.js:529:13)
  at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
  at ClangFormat.module.exports.ClangFormat.format (/packages/clang-format/lib/clang-format.coffee:79:16)
  at /packages/clang-format/lib/clang-format.coffee:18:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18901:35)
  at <embedded>:18639:65
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (<embedded>:66514:22)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (<embedded>:66305:28)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (<embedded>:15166:42)
  at HTMLDocument.<anonymous> (<embedded>:15069:65)

```

### Commands

```
  2x -7:28.1.0 core:backspace (input.hidden-input)
     -7:26.4.0 atomic-emacs:next-line (input.hidden-input)
     -7:24.6.0 grammar-selector:show (input.hidden-input)
     -7:23.2.0 editor:consolidate-selections (input.hidden-input)
     -7:23.2.0 core:cancel (input.hidden-input)
     -7:22.4.0 clang-format:format (input.hidden-input)
     -7:21.2.0 editor:consolidate-selections (input.hidden-input)
     -7:21.2.0 core:cancel (input.hidden-input)
     -7:18.2.0 intentions:highlight (input.hidden-input)
     -7:18 atomic-emacs:backward-kill-word (input.hidden-input)
     -7:17.8.0 datatip:toggle (input.hidden-input)
     -7:17.4.0 atomic-emacs:next-line (input.hidden-input)
  2x -7:17 core:delete (input.hidden-input)
     -7:15.6.0 core:save (input.hidden-input)
     -3:06.5.0 settings-view:open (input.hidden-input)
     -0:11.8.0 clang-format:format (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-syntax-dark 1.0.0 
atomic-emacs 0.11.0 
autocomplete-clang 0.11.3 
brahalla-syntax 0.5.0 
build 0.68.0 
build-cmake 0.10.1 
busy 0.7.0 
busy-signal 1.4.3 
clang-format 1.29.0 
emacs-tab 0.1.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.3 
language-babel 2.68.0 
language-cmake 0.3.0 
language-cpp14 0.6.2 
language-cuda 0.1.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-cpplint 2.0.1 
linter-ui-default 1.6.3 
MagicPython 1.0.11 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
nuclide 0.241.0 
nuclide-format-js 0.0.36 
one-dark-vivid-syntax 1.8.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
sync-settings 0.8.2 
tool-bar 1.1.0 
```

**Comment by AndrewSB** [comment]
I'm seeing this issue too. Also while using Nuclide to connect to a remote fs.
